### ISSUE TITLE
Config File Write Failed on CLI on Mac OS X High Sierra

### ISSUE THREAD

**Issue by david-mikulin** [dwavesystems/dwave-cloud-client#203] opened 2018-06-22 23:48 UTC
OS: Mac OS X High Sierra

When running 'dwave config create' I did not see some of the default values that I expected to see and ultimately, writing the config file failed.

Steps to reproduce:
1. Created virtual environment doing the following:
     virtualenv ocean
     cd ocean
     source ./bin/activate

2. Installed the Ocean SDK:
     pip install dwave-ocean-sdk

3. Tried to create configuration file:
     dwave config create

Please see the attached screenshot.

![screenshot_annotated](https://user-images.githubusercontent.com/24025168/41803278-fb364f92-763b-11e8-9662-d9857a74ec20.jpg)

**Comment by randomir** [comment] 2018-06-23 04:14
Duplicate of #197. Fixed in #205.

**Closed by randomir** 2018-06-23 04:14 UTC
